In [43]:
import pandas as pd
import numpy as np

In [44]:
data_df = pd.read_excel('sort.xlsx')
data_df

,Method,Wikipedia,Reddit,MOOC,LastFM,Enron,Social Evo.,UCI,Average Rank
0,JODIE-s,0.324137,0.390673,0.326339,0.465765,0.501337,0.626939,0.512211,0.449629
1,DyRep-s,0.608150,0.450409,0.555696,0.510416,0.576873,0.711534,0.478770,0.555978
2,TGN-s,0.795061,0.800981,0.631119,0.556728,0.695056,0.836718,0.733656,0.721331
3,JODIE-m,0.323070,0.389888,0.308108,0.463135,0.499669,0.609255,0.479058,0.438883
4,DyRep-m,0.583232,0.485268,0.520455,0.485076,0.577115,0.726964,0.470489,0.549800
5,TGN-m,0.778793,0.789366,0.621612,0.595782,0.694498,0.875255,0.722091,0.725342
6,JODIE-h,0.327506,0.366089,0.248831,0.421675,0.500667,0.524516,0.480346,0.409947
7,DyRep-h,0.588515,0.575414,0.544104,0.485089,0.566048,0.740749,0.488736,0.569808
8,TGN-h,0.701808,0.748685,0.514352,0.541621,0.656228,0.643645,0.642903,0.635606
9,JODIE-d,0.441499,0.459496,0.455705,0.339319,0.497070,0.515350,0.454295,0.451819
10,DyRep-d,0.581245,0.445349,0.540389,0.515913,0.585039,0.468328,0.503731,0.519999
11,TGN-d,0.705216,0.725305,0.461357,0.527944,0.672502,0.602379,0.642433,0.619591
12,EdgeBank-tw,0.417000,0.439000,0.189000,0.447000,0.484000,0.677000,0.491000,0.449143
13,EdgeBank-∞,0.435000,0.465000,0.219000,0.463000,0.468000,0.566000,0.515000,0.447286

In [45]:
data_df = data_df.drop(['Method', 'Average Rank'], axis=1)
data_df

    Wikipedia    Reddit      MOOC    LastFM     Enron  Social Evo.       UCI
0    0.324137  0.390673  0.326339  0.465765  0.501337     0.626939  0.512211
1    0.608150  0.450409  0.555696  0.510416  0.576873     0.711534  0.478770
2    0.795061  0.800981  0.631119  0.556728  0.695056     0.836718  0.733656
3    0.323070  0.389888  0.308108  0.463135  0.499669     0.609255  0.479058
4    0.583232  0.485268  0.520455  0.485076  0.577115     0.726964  0.470489
5    0.778793  0.789366  0.621612  0.595782  0.694498     0.875255  0.722091
6    0.327506  0.366089  0.248831  0.421675  0.500667     0.524516  0.480346
7    0.588515  0.575414  0.544104  0.485089  0.566048     0.740749  0.488736
8    0.701808  0.748685  0.514352  0.541621  0.656228     0.643645  0.642903
9    0.441499  0.459496  0.455705  0.339319  0.497070     0.515350  0.454295
10   0.581245  0.445349  0.540389  0.515913  0.585039     0.468328  0.503731
11   0.705216  0.725305  0.461357  0.527944  0.672502     0.602379  0.642433
12   0.417000  0.439000  0.189000  0.447000  0.484000     0.677000  0.491000
13   0.435000  0.465000  0.219000  0.463000  0.468000     0.566000  0.515000

In [46]:
auc = data_df.to_numpy()
auc

array([[0.32413701, 0.39067283, 0.32633926, 0.46576525, 0.50133725,
        0.62693911, 0.51221109],
       [0.60814996, 0.45040914, 0.55569576, 0.51041642, 0.57687293,
        0.71153377, 0.47877027],
       [0.7950611 , 0.80098094, 0.63111944, 0.55672836, 0.69505608,
        0.83671768, 0.73365561],
       [0.32307026, 0.38988842, 0.30810785, 0.46313525, 0.49966856,
        0.60925468, 0.47905821],
       [0.58323212, 0.48526837, 0.52045523, 0.48507558, 0.57711484,
        0.72696382, 0.4704885 ],
       [0.77879251, 0.78936614, 0.62161208, 0.59578159, 0.69449761,
        0.8752547 , 0.72209106],
       [0.32750557, 0.36608938, 0.24883131, 0.42167475, 0.50066683,
        0.52451633, 0.48034585],
       [0.5885147 , 0.57541416, 0.54410384, 0.48508916, 0.56604834,
        0.74074877, 0.48873634],
       [0.70180757, 0.74868491, 0.51435159, 0.54162133, 0.65622754,
        0.6436454 , 0.64290347],
       [0.44149926, 0.45949625, 0.45570451, 0.33931856, 0.49706991,
        0.51534965, 0.45429524],
       [0.58124479, 0.44534948, 0.54038879, 0.51591313, 0.58503912,
        0.46832802, 0.50373103],
       [0.70521648, 0.72530492, 0.46135735, 0.52794394, 0.67250172,
        0.60237908, 0.64243279],
       [0.417     , 0.439     , 0.189     , 0.447     , 0.484     ,
        0.677     , 0.491     ],
       [0.435     , 0.465     , 0.219     , 0.463     , 0.468     ,
        0.566     , 0.515     ]])

In [47]:
sort_idx = auc.shape[0] - auc.argsort(axis=0).argsort(axis=0)
sort_idx

array([[13, 12, 10,  9,  9,  8,  6],
       [ 5,  9,  3,  6,  7,  5, 12],
       [ 1,  1,  1,  2,  1,  2,  1],
       [14, 13, 11, 10, 11,  9, 11],
       [ 7,  6,  6,  8,  6,  4, 13],
       [ 2,  2,  2,  1,  2,  1,  2],
       [12, 14, 12, 13, 10, 12, 10],
       [ 6,  5,  4,  7,  8,  3,  9],
       [ 4,  3,  7,  3,  4,  7,  3],
       [ 9,  8,  9, 14, 12, 13, 14],
       [ 8, 10,  5,  5,  5, 14,  7],
       [ 3,  4,  8,  4,  3, 10,  4],
       [11, 11, 14, 12, 13,  6,  8],
       [10,  7, 13, 11, 14, 11,  5]])

In [48]:
sort_idx.mean(axis=1)

array([ 9.57142857,  6.71428571,  1.28571429, 11.28571429,  7.14285714,
        1.71428571, 11.85714286,  6.        ,  4.42857143, 11.28571429,
        7.71428571,  5.14285714, 10.71428571, 10.14285714])

In [49]:
sort_idx.mean(axis=1).argsort().argsort() + 1

array([ 9,  6,  1, 12,  7,  2, 14,  5,  3, 13,  8,  4, 11, 10])